/**
 * DO NOT CHANGE THIS FILE!
 * This file is automatically generated.
 */
import { sql_delete, sql_insert, sql_query, sql_update } from "@blendsdk/sqlkit";
import { ISysUserRole } from "../dbtypes";

/**
 * Insert a record into the sys_user_role relation
 */
export const insertIntoSysUserRole = sql_insert<ISysUserRole, ISysUserRole>("sys_user_role");

/**
 * The IGetSysUserRoleByUserRoleId interface.
 *
 * @interface IGetSysUserRoleByUserRoleId
 * @export
 */
export interface IGetSysUserRoleByUserRoleId {
	/**
	 * @type {number}
	 * @memberof IGetSysUserRoleByUserRoleId
	 */
	user_role_id?: number;
}

/**
 * Gets a record from the sys_user_role relation
 */
export const getSysUserRoleByUserRoleId = sql_query<ISysUserRole, IGetSysUserRoleByUserRoleId>(
	"SELECT * FROM sys_user_role WHERE user_role_id = :user_role_id",
	{ single: true }
);

/**
 * The IUpdateSysUserRoleByUserRoleId interface.
 *
 * @interface IUpdateSysUserRoleByUserRoleId
 * @export
 */
export interface IUpdateSysUserRoleByUserRoleId {
	/**
	 * @type {number}
	 * @memberof IUpdateSysUserRoleByUserRoleId
	 */
	user_role_id?: number;
}

/**
 * Updates a record from the sys_user_role relation
 */
export const updateSysUserRoleByUserRoleId = sql_update<ISysUserRole, ISysUserRole, IUpdateSysUserRoleByUserRoleId>(
	"sys_user_role",
	{ single: true }
);

/**
 * The IDeleteSysUserRoleByUserRoleId interface.
 *
 * @interface IDeleteSysUserRoleByUserRoleId
 * @export
 */
export interface IDeleteSysUserRoleByUserRoleId {
	/**
	 * @type {number}
	 * @memberof IDeleteSysUserRoleByUserRoleId
	 */
	user_role_id?: number;
}

/**
 * Deletes a record from the sys_user_role relation
 */
export const deleteSysUserRoleByUserRoleId = sql_delete<ISysUserRole, IDeleteSysUserRoleByUserRoleId>("sys_user_role", {
	single: true
});
